list="2d_surface.py \
3d_flower.py \
3d_flowerv1.py \
3d_flowerv2.py \
3d_flowerv3.py \
3d_flowerv4.py \
3d_flowerv5.py \
3d_flowerv9.py \
3dsolid.py \
abstract_art.py \
amazing_ellipse.py \
aperiodic_sine.py \
artificial_artist.py \
artificial_artistv2.py \
asym_fractal_tree.py \
bezier.py \
bicusp3d.py \
bicusp.py \
bilope.py \
bin_vase.py \
blinking_ball.py \
blurry_beautiful_helix.py \
cardiod3d_cross.py \
cardiod3dv1.py \
cardiod.py \
ccc.py \
chasing_heart.py \
circle_generator.py \
circle_ladder.py \
circle_on_circle.py \
circle_on_sphere.py \
circle.py \
circling_triangle.py \
closing_opening_circle.py \
closing_opening_ellipse.py \
colorcube.py \
colorCube.py \
ColorCube.py \
colorcube_spewing_spiral.py \
color_evolving.py \
criss_cross_surface.py \
crossing_lines_hypocycloid.py \
crown_circling_double.py \
crown_circling.py \
cubic_mandelbrot.py \
cubic_mandelbrot_v2.py \
curve10_generator.py \
curve1_generator.py \
curve2_generator.py \
curve3_generator.py \
curve4_generator.py \
curve5_generator.py \
curve6_generator.py \
curve7_generator.py \
curve8_generator.py \
curve9_generator.py \
curve_ladder.py \
curvy_ortho_heart.py \
dancing_dodecahedron.py \
dancing_quad_spiral.py \
dancing_spiral.py \
dodecahedron.py \
double_cardiod.py \
double_cube.py \
double_lemniscus.py \
double_rotating_sphere.py \
dragon.py \
dragon_string.py \
draw_dragon.py \
draw_h.py \
draw_module_example.py \
ellipse.py \
ellipsev1.py \
ellipsev2.py \
ellipsoidv1.py \
ellipsoidv2.py \
ellipsoidv3.py \
ellipsoidv4.py \
enveloping_cardiod.py \
epicycloid_generator.py \
expanding_circle.py \
fat_torus.py \
fat_torusv2.py \
fern.py \
fig8.py \
figOeight_circling.py \
figure_eight2.py \
figure_eight.py \
figure_of_eight.py \
flower.py \
flying_plane.py \
fourier1.py \
fractalgon.py \
fractal_popcorn1.py \
fractal_popcorn.py \
fractal_tree.py \
graphic.py \
graycode.py \
half_wire_ellipse.py \
heart2.py \
heart3.py \
heart4.py \
heart.py \
heart_torus.py \
helix.py \
helloworld_opengl.py \
helloworld.py \
hexgon1.py \
hexgon2.py \
hexgon.py \
hilbert2d_1.py \
hilbert2d3.py \
hilbert2d.py \
hilbert_koch.py \
hilbertv0.py \
hilbertv1.py \
hilbertv2.py \
hilbertv3.py \
hilbertv4.py \
hypocycloid_generator.py \
hypocycloid_outer.py \
hypocycloid.py \
inside_out_torus.py \
interrupt.py \
koch1.py \
koch2.py \
koch3.py \
koch.py \
lemniscus.py \
lesson3.py \
linden_koch.py \
lindenmayer.py \
lindenmayerv1.py \
linden_moore.py \
linden_sierspinski.py \
line2.py \
line3.py \
line.py \
lopsided_lemniscus.py \
magdalene_curve.py \
mandelbrot16.py \
mandelbrot1.py \
mandelbrot2.py \
mandelbrot3.py \
mandelbrot4.py \
mandelbrot_bmp.py \
mandelbrot_bw1.py \
mandelbrot_bw.py \
mandelbrot_by_complex.py \
mandelbrot.py \
mandelbrotset.py \
mandelbrot_shader.py \
mandelbrot_tkinter1.py \
mandelbrot_tkinter.py \
mandelbrot_wiki.py \
mobius.py \
mobiusv1.py \
morphing_cusp.py \
morphing_magdalene_curve.py \
morphing_sine.py \
mouse_rotated_cube.py \
moving_circle.py \
moving_colour_sine.py \
moving_ellipse.py \
moving_flower.py \
moving_hypocycloid.py \
moving_ladder.py \
moving_sine.py \
moving_spiral_tangent.py \
moving_spiral_triangle.py \
moving_spiral_triangle_surface.py \
moving_twinning_colour.py \
multi_sinusoidal_solid.py \
multi_sinusoidal_solidv2.py \
multi_sinusoidal_solidv3.py \
multi_sinusoidal_solidv4.py \
multi_sinusoidal_solidv5.py \
multi-tetrahedron-multicolor.py \
multi-tetrahedron.py \
my3cusp.py \
mysansagraphic.py \
newton_raphson.py \
newton_raphsonv1.py \
newton_raphsonv2.py \
newton_raphsonv3.py \
newton_raphsonv4.py \
ngon_generator.py \
orthonormal_heart.py \
overlapping_circle1.py \
overlapping_circle2.py \
overlapping_circle.py \
pentagon_triangle_orig.py \
pentagon_with_hole.py \
penta_lemnicus1.py \
penta_lemnicus.py \
petal_on_sphere.py \
phoenix.py \
pinched_donut.py \
pinched_ellipsoid.py \
planecircle.py \
planeobject.py \
plane_of_helix.py \
plot.py \
polygonal_slicing.py \
polygon_recursion.py \
polyhedral_surface.py \
porcupine.py \
prime_list.py \
pumping_sphere.py \
pygame_line1.py \
pygame_line.py \
pygame_mandelbrot.py \
quad_donut.py \
quad_lemnicus.py \
quadratic_mandelbrot.py \
random_graphics.py \
recurring_spiral_generator.py \
recursion_tree_asym.py \
recursion_tree.py \
repeated_3cusp.py \
repeated_4cusp.py \
ring_of_cirle.py \
rotated_3cuspy.py \
rotated_4cuspy.py \
rotating_2torus.py \
rotating_cardiod3d_line.py \
rotating_cardiod3d.py \
rotating_cardiod3d_triangulate.py \
rotating_circle.py \
rotating_cube.py \
rotating_disk.py \
rotating_donut.py \
rotating_double_cardiod.py \
rotating_ellipse_plane.py \
rotating_ellipse.py \
rotating_globe.py \
rotating_helix.py \
rotating_hypocycloid.py \
rotating_line.py \
rotating_mobius.py \
rotating_mobius_v2.py \
rotating_multiprong.py \
rotating_planar_vector.py \
rotating_plane.py \
rotating_plane_single.py \
rotating_quadratic.py \
rotating_sphere.py \
rotating_spiral_tangent_generatev2.py \
rotating_spoke.py \
rotating_star_torus.py \
rotating_star_torus_v2.py \
rotating_toroid.py \
rotating_torus_orig.py \
rotating_tricusp.py \
rotating_triple_torus.py \
rotating_triple_torus_v2.py \
rotating_wierd_torus1.py \
rotating_wierd_torus.py \
running_spiral.py \
running_worm.py \
Settings.py \
sierpinski1.py \
sierspinski.py \
sierspinskiv2.py \
sierspinskiv3.py \
simple_asymmetric_spiral.py \
simple_graphic_demo.py \
simple_helix.py \
simpleHilbertCurve.py \
simple_spheroidal_spiral.py \
simple_spoke.py \
simple_winding.py \
simple_xy_swap.py \
simple_xy_swapv1.py \
sine_mandel2_1.py \
sine_mandel2_2.py \
sine_mandel2.py \
sine_mandel3.py \
sine_mandel4.py \
sine_mandel6_1.py \
sine_mandel6.py \
sine_mandel.py \
single_layer_ellipse.py \
single_slice_ellipse.py \
sinusoidal_surface.py \
sinusoidal_winding.py \
sinusoid_surface_depth_test.py \
sinusoid_surface_without_alpha_blend.py \
solar_flare_variation.py \
solid_torus.py \
solidv10.py \
solidv11.py \
solidv11_skeleton.py \
solidv6.py \
solidv7.py \
solidv8.py \
solidv9.py \
spheremonic.py \
spherical_pentagon.py \
spherical_tesselation.py \
spherical_triangulation.py \
spheroid_sinsoidal_surface.py \
spheroid_surfing.py \
spiral3d_function.py \
spiral3d_object.py \
spiral_flare_variation.py \
spiral_generator.py \
spiral_n_angle.py \
spiral.py \
spiral_spoke.py \
spiral_spoke_v2.py \
spiral_strand.py \
spiral_tangent_generator.py \
spiral_tangent_generatorv2.py \
spiral_triangle.py \
square.py \
star1.py \
star.py \
super_helix_beauty.py \
super_ugly_petal_surface.py \
surface_line.py \
surface_linev1.py \
surface_linev22_1.py \
surface_linev22_2.py \
surface_linev22.py \
surface_linev2.py \
surface_linev3.py \
surface_linev4.py \
surface_linev5.py \
surface_linev6_1.py \
surface_linev6_2.py \
surface_linev6.py \
tdemo_fractalcurves.py \
test.py \
tetrahedron.py \
toroid1_generator.py \
toroid_generator.py \
torus.py \
torusv1.py \
torusv2.py \
torusv3.py \
trefoil1.py \
trefoil.py \
triangle_recursion.py \
triangular_sequence.py \
tricusp.py \
trilope.py \
triple_donut.py \
triple_lemnicus.py \
twisting_ladder_surface_color.py \
twisting_ladder_surface.py \
twisting_ladder_surface_v1.py \
twisting_ladder_surface_v2.py \
twisting_ribbon_surface.py \
twisting_surface_v1.py \
wavy_ortho_heart.py \
winding_helix1.py \
winding_helix2.py \
winding_helix.py \
wired_torus.py \
wireicosahedron.py \
wiresphere.py \
wiretorus.py \
wxglcanvas_opengl.py \
x_vs_y_oscilloscope.py"

source venv2/bin/activate

for item in $list
do
	echo $item
	python $item
done
